### ISSUE TITLE
Rank's das Organizações

### ISSUE THREAD

**Issue by tropadoeurico** [rrafaelcardosoo/bugs-reports-utopia#3]
EXISTEM ALGUMAS ORGS QUE ESTÃO DUPLICADAS!

![imagem_2024-01-22_170600372](https://github.com/rrafaelcardosoo/bugs-reports-utopia/assets/143232895/6a0a16a3-09c8-4010-910a-d3c95147540a)

**Comment by rrafaelcardosoo** [comment]
Olá boa tarde , desde de mais agradecemos o seu report do bug , teremos noção de tal no entanto iremos resolver.
