### ISSUE TITLE
redes de pesca

### ISSUE THREAD

**Issue by cabecaoOFC1** [rrafaelcardosoo/bugs-reports-utopia#5]
quando se vai a pesca de vez em quando ou melhor dizendo muito frequentemente se perde duas redes ou porque te levantaste da cadeirq pra ir a bagageira guardar o peixe ou porque saiste da zona de pesca mesmo ja nem sequer tares a pescar, porque sempre que tu vais descarregar o barco e necessario ir ao porto e quando sais da zona de pesca perdes mais uma rede depois de vez em quando perdes duas redes quando so utilizaste uma, e assim vais se perdendo quase metade das redes que compramos e tamos a perde dinherio e a gastar atoa e acho que a pesca e um trabalho bastante bom que devia ter mais procura mas assim as pessoas com menos dinheiro nao conseguem aproveitar tudo

**Comment by rrafaelcardosoo** [comment]
Olá boa noite , desde de mais agradecemos o seu report do bug , iremos resolver.
